spring:
  application:
    name: cloud-classroom
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      enabled: true
      max-request-size: 100MB
      max-file-size: 10MB
      file-size-threshold: 10MB
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
#    filters: stat,wall,log4j
#jwt
jwt:
  id: gyskdatacagejwt
  secret: 7786df7fc3a34e26a61c034d5ec8245d
  refresh-interval: 604800000
  refresh-ttl: 604800000
  enable: true
  ttl: 604800000
  token:
    secret: mySecret
    expiration: 86400
