server:
  port: 8096
spring:
  application:
    name: cloud-classroom
  profiles:
    active: dev
  servlet:
    multipart:
      #上传一个文件最大值  默认是1MB
      max-file-size: 10MB
      #上传多个文件最大值  默认是10MB
      max-request-size: 100MB
#knife4j:
#  basic:
#    enable: true #输入下面的用户名密码查看接口文档
#    username: nkdykt
#    password: nkdykt

